module.exports = {
  projectName: "vam-plugin-bim",
  passphrase: "",
  cluster: [],
  dev: {
    name: "开发环境",
    host: "",
    port: 22,
    username: "root",
    password: "",
    distPath: "dist",
    webDir: "",
    bakDir: "",
    isRemoveRemoteFile: true,
    isRemoveLocalFile: false,
  },
  test: {
    name: "测试环境",
    host: "",
    port: 22,
    username: "root",
    password: "",
    distPath: "dist",
    webDir: "",
    bakDir: "",
    isRemoveRemoteFile: true,
    isRemoveLocalFile: false,
  },
  prod: {
    name: "生产环境",
    host: "",
    port: 22,
    username: "root",
    password: "",
    distPath: "dist",
    webDir: "",
    bakDir: "",
    isRemoveRemoteFile: true,
    isRemoveLocalFile: false,
  },
};
